### ISSUE TITLE
BaasicClient doubles api key when returning secureApiUrl 

### ISSUE THREAD

**Issue by MarioDudjak** [Baasic/baasic-sdk-net#1]
Issue tracker is used for reporting bugs and requesting new features. Please use [StackOverflow](https://stackoverflow.com) or [Google Groups](https://groups.google.com/forum/#!forum/baasic-baas) for supporting issues.

## General Information 
BaasicClient doubles api key when returning secureApiUrl. 
Example of use:

public Repository(IBaasicClient baasicClient)
        {
            BaasicClient = baasicClient;
         }
BaasicClient.GetSecureApiUrl("resources/");  

-- Returns https://api.baasic.com/version/api-key/api-key

## Expected Behavior
E.g. secure api url should be like: https://api.baasic.com/version/api-key/api-key

## Current Behavior
Secure api url looks like: https://api.baasic.com/version/api-key/

## Steps to Reproduce

1.
2.
3.
4.

## Specifications

  - ApiKey:
  - Version:
  - Url:
  - SDK:

**Comment by khorvat** [comment]
This issue has been fixed in 0.8.156 version.
